name: Build nexus applications
on:
  workflow_dispatch:
  push:
    paths:
      - 'nexus/**'
      - '!nexus/README.md'
      - '.github/workflows/nexus.yml'
jobs:
  test-app:
    name: Test app
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        axis-os: ["12.8.54"]
        arch: ["armv7hf", "aarch64"]
    env:
      EXREPO: acap-native-examples
      EXNAME: nexus
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3

      - name: Build ${{ env.example }} application
        env:
          example: object-detector
          imagetag: ${{ env.EXREPO }}_object-detector:${{ matrix.arch }}
        run: |
          docker image rm -f $imagetag
          cd $EXNAME/acap-communication/$example
          docker build --no-cache --tag $imagetag --build-arg ARCH=${{ matrix.arch }} .
          docker cp $(docker create $imagetag):/opt/app ./build
          cd ../../..
          docker image rm -f $imagetag

      - name: Build ${{ env.example }} application
        env:
          example: object-consumer
          imagetag: ${{ env.EXREPO }}_object-consumer:${{ matrix.arch }}
        run: |
          docker image rm -f $imagetag
          cd $EXNAME/acap-communication/$example
          docker build --no-cache --tag $imagetag --build-arg ARCH=${{ matrix.arch }} .
          docker cp $(docker create $imagetag):/opt/app ./build
          cd ../../..
          docker image rm -f $imagetag

      - name: Build ${{ env.example }} application
        env:
          example: memory-cpu-utilization
          imagetag: ${{ env.EXREPO }}_memory-cpu-utilization:${{ matrix.arch }}
        run: |
          docker image rm -f $imagetag
          cd $EXNAME/$example
          docker build --no-cache --tag $imagetag --build-arg ARCH=${{ matrix.arch }} .
          docker cp $(docker create $imagetag):/opt/app ./build
          cd ../..
          docker image rm -f $imagetag
